export const genres = [
	"action",
	"adult",
	"adventure",
	"anime",
	"children",
	"comedy",
	"crime",
	"diy",
	"drama",
	"espionage",
	"family",
	"fantasy",
	"food",
	"history",
	"horror",
	"legal",
	"medical",
	"music",
	"mystery",
	"nature",
	"romance",
	"science-fiction",
	"sports",
	"supernatural",
	"thriller",
	"travel",
	"war",
	"western",
];

export const genresMap: { [key: string]: string } = {
	action: "Ação",
	adult: "Adulto",
	adventure: "Aventura",
	anime: "Anime",
	children: "Infantil",
	comedy: "Comédia",
	crime: "Crime",
	diy: "DIY",
	drama: "Drama",
	espionage: "Espionagem",
	family: "Familia",
	fantasy: "Fantasia",
	food: "Comida",
	history: "História",
	horror: "Terror",
	legal: "Jurídico",
	medical: "Médico",
	music: "Musical",
	mystery: "Mistério",
	nature: "Natureza",
	romance: "Romance",
	"science-fiction": "Ficção científica",
	sports: "Esporte",
	supernatural: "Sobre Natural",
	thriller: "Ação",
	travel: "Viagem",
	war: "Guerra",
	western: "Ocidente",
};