/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as ShowsIndexImport } from './../routes/_shows/index'
import { Route as ShowsShowIdImport } from './../routes/_shows/$showId'

// Create/Update Routes

const ShowsIndexRoute = ShowsIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShowsShowIdRoute = ShowsShowIdImport.update({
  path: '/$showId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shows/$showId': {
      preLoaderRoute: typeof ShowsShowIdImport
      parentRoute: typeof rootRoute
    }
    '/_shows/': {
      preLoaderRoute: typeof ShowsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ShowsShowIdRoute,
  ShowsIndexRoute,
])

/* prettier-ignore-end */
